---
- name: Add Docker apt key.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  ignore_errors: True 

- name: Add Docker repository.
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable" 
    state: present
    update_cache: true

- name: Install docker
  apt:
    name: docker-ce
    state: latest 


- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.21.2/docker-compose-Linux-x86_64 
    dest: /usr/local/bin/docker-compose

- name: Make docker-compose executable
  file:
    path: /usr/local/bin/docker-compose
    mode: a+x

  
