---
# tasks file for apt



- name: Install necessary libs
  apt:
    name: "{{ apt_item }}"
    state: latest 
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - git 
    - python3 
    - python3-dev 
    - python3-pip 
    - tree
    - virtualbox
    - vagrant 
  loop_control:
    loop_var: apt_item

- include: docker.yml
- include: vim.yml

