---
- name: Development Environment Install
  hosts: 127.0.0.1
  connection: local

  tasks: 
    - name: Roles to include
      include_role:
        name: "{{ role_item }}"

      loop:
       # - apt
       # - pip 
        - third_party
      loop_control:
        loop_var: role_item

    
